run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - gosimple
    - govet
    - misspell
    - revive
    - unused
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
issues:
  exclude-dirs:
    - '.*pkg/mod.*'
    - '.*go/.*'
    - '.*Cellar.*'             # Skip Homebrew Go installation directory
    - '.*libexec.*'
  exclude-files:
    - '.*toolchain@.*'