project_name: kanvas-snapshot

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w
      - -X main.GithubToken={{.Env.GITHUB_TOKEN}}
      - -X main.MesheryCloudApiCookie={{.Env.MESHERY_CLOUD_API_COOKIE}}
      - -X main.MesheryApiCookie={{.Env.MESHERY_API_COOKIE}}
      - -X main.Owner={{.Env.OWNER}}
      - -X main.Repo={{.Env.REPO}}
      - -X main.Workflow={{.Env.WORKFLOW}}
      - -X main.Branch={{.Env.BRANCH}}
      - -X main.MesheryCloudApiBaseUrl={{.Env.MESHERY_CLOUD_API_BASE_URL}}
      - -X main.MesheryApiBaseUrl={{.Env.MESHERY_API_BASE_URL}}
      - -X main.SystemID={{.Env.SYSTEM_ID}}

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - 386
      - amd64
      - arm
      - arm64

    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - id: stable
    name_template: >-
      {{ .ProjectName }}_{{.Version}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: "Kanvas Snapshot {{.Tag}}"
