project_name: kanvas-snapshot
version: 2
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.providerToken={{.Env.PROVIDER_TOKEN}}
      - -X main.MesheryCloudApiBaseUrl="https://meshery.layer5.io"
      - -X main.MesheryApiBaseUrl="https://playground.meshery.io"
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: '{{ .ProjectName }}'

extra_files:
  - source: plugin.yaml                    # Adds plugin.yaml to dist
    destination: .
  - source: LICENSE                        # Adds LICENSE to dist
    destination: .
  - source: install-binary.sh              # Adds install-binary.sh to dist
    destination: .

archives:
  - format: tar.gz
    wrap_in_directory: true                 # Ensures all files are in a top-level directory
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - plugin.yaml                         # Include plugin.yaml
      - LICENSE                             # Optional, include any other files
      - install-binary.sh                   # Optional install script

