name: "kanvas-snapshot"
version: "0.2.0"
usage: "Generate a visual snapshot of your Helm chart as a Meshery Snapshot"
description: "A Helm plugin to generate Kanvas Snapshots from Helm charts using a custom Go binary"
command: "$HELM_PLUGIN_DIR/bin/kanvas-snapshot"
platformCommand: 
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/kanvas-snapshot"
  - os: darwin
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/kanvas-snapshot"
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/kanvas-snapshot.exe"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
  uninstall: echo "Snapshot plugin uninstalled."
